export default {
  ALL_COUNTRIES_FETCH: 'ALL_COUNTRIES_FETCH',
  ALL_COUNTRIES_FETCH_SUCCESS: 'ALL_COUNTRIES_FETCH_SUCCESS',
  ALL_COUNTRIES_FETCH_FAILURE: 'ALL_COUNTRIES_FETCH_FAILURE',

  COUNTRY_FETCH: 'COUNTRY_FETCH',
  COUNTRY_FETCH_SUCCESS: 'COUNTRY_FETCH_SUCCESS',
  COUNTRY_FETCH_FAILURE: 'COUNTRY_FETCH_FAILURE'
}